title: Mary Laheen Architects
email: mlaheenarchitects@eircom.net
description: >- # this means to ignore newlines until "baseurl:"
   Architectural practice
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mlaheenarchitects.ie"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-contentblocks
  - jekyll-feed

destination: docs

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - etc/
